name: "build-and-deploy"

on: "push"

jobs:
  build-nix:
    runs-on: "ubuntu-latest"
    container:
      image: "ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-23.08"

    steps:
    - uses: actions/checkout@v4
    - run: python3 ci-build.py
