name: "build-and-deploy"

on: "push"

jobs:
  pull-repo:
    runs-on: "ubuntu-latest"

    steps:
    -  uses: cachix/install-nix-action@v27
    -  run: nix-shell -p awscli2 --command "aws s3 cp s3://green-updater/flatpak repo"
    -  uses: "actions/upload-artifact@v4"
       with:
         name: "pre-build repo"
         path: "repo"
         if-no-files-found: error

  build-repo:
    needs: pull-repo
    runs-on: "ubuntu-latest"
    container:
      image: "ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-23.08"
      options: --privileged

    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: "pre-build repo"

    - run: flatpak remote-add --if-not-exists --user flathub "https://dl.flathub.org/repo/flathub.flatpakrepo"
    - run: pip install aiohttp toml
    - run: python3 ci-build.py

  push-repo:
    needs: build-repo
    runs-on: "ubuntu-latest"

    steps:
    -  uses: cachix/install-nix-action@v27
    -  run: nix-shell -p awscli2 --command "aws s3 sync repo s3://green-updater/flatpak"
