name: "build-and-deploy"

on: "push"

jobs:
  push-repo-file:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v4

    -  uses: cachix/install-nix-action@v27
       with:
         nix_path: "nixpkgs=channel:nixos-24.05"

    - name: "login to AWS"
      uses: "aws-actions/configure-aws-credentials@v4"
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    -  run: nix-shell -p awscli2 --command "aws s3 cp green-repo.flatpakrepo s3://green-updater/green-repo.flatpakrepo"

  pull-repo:
    runs-on: "ubuntu-latest"

    steps:
    -  uses: cachix/install-nix-action@v27
       with:
         nix_path: "nixpkgs=channel:nixos-24.05"

    - name: "login to AWS"
      uses: "aws-actions/configure-aws-credentials@v4"
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    -  run: mkdir repo && touch repo/.keep
    -  run: nix-shell -p awscli2 --command "aws s3 cp s3://green-updater/flatpak/ repo --recursive"

    -  uses: "actions/upload-artifact@v4"
       with:
         name: "pre-build repo"
         path: "repo"

  build-repo:
    needs: pull-repo
    runs-on: "ubuntu-latest"
    container:
      image: "ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-23.08"
      options: --privileged

    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: "pre-build repo"
        path: "repo"

    - run: mkdir repo -p

    - run: flatpak remote-add --if-not-exists --user flathub "https://dl.flathub.org/repo/flathub.flatpakrepo"
    - run: pip install aiohttp toml
    - run: python3 ci-build.py
    - run: flatpak build-bundle repo io.github.urlordjames.GreenUpdater.flatpak io.github.urlordjames.GreenUpdater
    - run: flatpak build-update-repo --generate-static-deltas --prune repo

    -  uses: "actions/upload-artifact@v4"
       with:
         name: "post-build repo"
         path: "repo"
         if-no-files-found: error

  push-repo:
    needs: build-repo
    runs-on: "ubuntu-latest"

    steps:
    -  uses: cachix/install-nix-action@v27
       with:
         nix_path: "nixpkgs=channel:nixos-24.05"

    - name: "login to AWS"
      uses: "aws-actions/configure-aws-credentials@v4"
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - uses: actions/download-artifact@v4
      with:
        name: "post-build repo"
        path: "repo"

    -  run: nix-shell -p awscli2 --command "aws s3 sync repo s3://green-updater/flatpak"
