name: "build-and-deploy"

on: "push"

jobs:
  build-and-deploy:
    runs-on: "ubuntu-latest"
    container:
      image: "ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-23.08"
      options: --privileged

    steps:
    - uses: actions/checkout@v4
    - run: flatpak remote-add --if-not-exists --user flathub "https://dl.flathub.org/repo/flathub.flatpakrepo"
    - run: pip install aiohttp toml
    - run: python3 ci-build.py
