name: "build-and-deploy"

on: "push"

jobs:
  build-nix:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - run: nix develop --command ./build.sh
