name: "build-and-deploy"

on: "push"

jobs:
  build-repo:
    runs-on: "ubuntu-latest"
    container:
      image: "ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08"
      options: --privileged

    steps:
    - uses: actions/checkout@v4

    - run: flatpak remote-add --if-not-exists --user flathub "https://dl.flathub.org/repo/flathub.flatpakrepo"
    - run: pip install aiohttp toml

    - run: echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

    - run: python3 ci-build.py
    - run: "flatpak build-bundle repo --runtime-repo='https://dl.flathub.org/repo/flathub.flatpakrepo' --gpg-sign=urlordjames io.github.urlordjames.GreenUpdater.flatpak io.github.urlordjames.GreenUpdater"
    - run: flatpak build-update-repo --gpg-sign=urlordjames --prune repo

    -  uses: "actions/upload-artifact@v4"
       with:
         name: "post-build repo"
         path: "repo"
         if-no-files-found: error

  push-repo:
    needs: build-repo
    runs-on: "ubuntu-latest"

    steps:
    -  uses: cachix/install-nix-action@v27
       with:
         nix_path: "nixpkgs=channel:nixos-24.05"

    - name: "login to AWS"
      uses: "aws-actions/configure-aws-credentials@v4"
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - uses: actions/download-artifact@v4
      with:
        name: "post-build repo"
        path: "repo"

    -  run: nix-shell -p awscli2 --command "aws s3 sync repo s3://green-updater/flatpak --delete"
